### ISSUE TITLE
[17.0] fs_attachment unable to save Attachment Rules

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/storage#362]
## Module
fs_attachment

## Describe the bug
https://app.screencastify.com/v3/watch/lNaDUColgK4gQw8GMvJY
Can't save additional attachment rules error seems incorrect.
@astirpe could you maybe help with a PR here?

**Additional context**
In addition I think we should consider adding .scss to the DB by default. This is used by Odoo website.
@lmignon could you maybe judge this?

**Comment by astirpe** [comment]
Seems the additional attachment rules issue is caused by the constraint that doesn't work well because of the constrained fields that are not stored on db (maybe issue of module server_environment?)
In https://github.com/OCA/storage/pull/363 there's a quick fix, I didn't find a better way to solve it.

CC @CasVissers-360ERP
