### ISSUE TITLE
runbot configuration

### ISSUE THREAD

**Issue by rousseldenis** [OCA/storage#7]
Hi @gurneyalex, runbot for this (new) repo seems buggy.

Could you check ?

**Comment by rousseldenis** [comment]
@gurneyalex See logs : https://runbot2.odoo-community.org/runbot/static/build/3387775-4-5c256e/logs/job_10_test_base.txt

And https://runbot2.odoo-community.org/runbot/static/build/3387775-4-5c256e/logs/job_20_test_all.txt

I think it's about docker

**Comment by gurneyalex** [comment]
@rousseldenis yes the issue comes from [this line in travis.yml|https://github.com/OCA/storage/blob/e9ae4bd810ec108f8a830a849ed3e58640805a01/.travis.yml#L40] : the before_install section is executed by travis2docker in the bulding of the docker image. It cannot include `docker run` commands

My guess is you would need to find another way of running the sftp server without docker, if you want to test this on runbot.

**Comment by gurneyalex** [comment]
maybe @moylop260 has an idea.

**Comment by rousseldenis** [comment]
@sebastienbeau As you did the change in https://github.com/OCA/storage/commit/cf7c19dc2457f2d7d5e3965eb49e8efbef756916

**Comment by gurneyalex** [comment]
on the other hand, I'm really not fond of letting any repo run anything via docker on the runbot. 
Main reason is that we don't have a way on the runbot module to stop these side services, and it would be so easy to have an open mail relay / bitcoin miner run on the infrastructure -> I'm not too much in favor of working to get it to run this way. Now if you want to take the opportunity of the code sprint to discuss this, come :)

**Comment by rousseldenis** [comment]
As discussed with @sebastienbeau, the idea is to run tests with mock as that docker was a helper to test sftp connections.

**Comment by moylop260** [comment]
Hi @rousseldenis 
Runbot is using a `docker container` without `privileged` flag.
So, we can not run docker into docker in OCA's runbot.

We have created a environment variable 
 - https://github.com/OCA/runbot-addons/blob/ad499d746dc23f0aa6ab68ccd44f46db036b5a0a/runbot_travis2docker/models/runbot_build.py#L249

In order to skip process for runbot.

I mean, you can validate from .travis.yml file something like:
  - `if $RUNBOT <> "1" then; docker run...`

Or you can avoid using a docker command using a [mock](https://docs.python.org/3/library/unittest.mock.html) instead.

**Comment by simahawk** [comment]
@rousseldenis @sebastienbeau ping :wink: 
`master` is red and validating PRs turns tricky :disappointed:

**Comment by lmignon** [comment]
@simahawk The problem comes from the docker service declared into travis.yml https://github.com/OCA/storage/blob/12.0/.travis.yml#L9 we must remove the sftp server https://github.com/OCA/storage/blob/12.0/.travis.yml#L41 and mock the calls to the sftp server into the tests

**Comment by simahawk** [comment]
I can give a try to vcr

**Comment by simahawk** [comment]
hmm FTP seems not supported, I check for simple mocking
